services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=platzi_play_db'
      - 'POSTGRES_PASSWORD=3lm3j0rs'
      - 'POSTGRES_USER=alenadro'
    ports:
      - '5432:5432'
      - volumes:
          - pgdata:/data/postgres

vulumes:
  pgdata: